AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for sistema-votacao

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  EleicaoApi:
      Type: AWS::Serverless::Api
      Properties:
        Name: API Sistema de Votacao
        StageName: prod

  EleicaoTable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: sv_eleicao
        BillingMode: PAY_PER_REQUEST 
        AttributeDefinitions:
            -
              AttributeName: "id"
              AttributeType: "S"
            -
              AttributeName: "dataInclusao"
              AttributeType: "S"
        KeySchema:
            -
              AttributeName: "id"
              KeyType: "HASH"
            -
              AttributeName: "dataInclusao"
              KeyType: "RANGE"
  EleitorTable:
    Type: AWS::DynamoDB::Table
    Properties:
          TableName: sv_eleitor
          BillingMode: PAY_PER_REQUEST 
          AttributeDefinitions:
              -
                AttributeName: "eleicaoId"
                AttributeType: "S"
              -
                AttributeName: "id"
                AttributeType: "S"
          KeySchema:
              -
                AttributeName: "eleicaoId"
                KeyType: "HASH"
              -
                AttributeName: "id"
                KeyType: "RANGE"


  NovaEleicaoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: app/built
      Handler: ./functions/novaEleicaoFunction.lambdaHandler
      Runtime: nodejs14.x
      MemorySize: 256
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Events:
        ApiGatewayEvent:
          Type: Api 
          Properties:
            Path: /eleicoes
            Method: post
            RestApiId: !Ref EleicaoApi

  NovoEleitorFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: app/built
      Handler: ./functions/novoEleitorFunction.lambdaHandler
      Runtime: nodejs14.x
      MemorySize: 256
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      Events:
        ApiGatewayEvent:
          Type: Api 
          Properties:
            Path: /eleicoes/{eleicaoId}/eleitores
            Method: post
            RestApiId: !Ref EleicaoApi

  ConsultaEleitorFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: app/built
      Handler: ./functions/consultaEleitorFunction.lambdaHandler
      Runtime: nodejs14.x
      MemorySize: 256
      Policies:
        - arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
      Events:
        ApiGatewayEvent:
          Type: Api 
          Properties:
            Path: /eleicoes/{eleicaoId}/eleitores/{id}
            Method: get
            RestApiId: !Ref EleicaoApi